### ISSUE TITLE
Client IP is always 127.0.0.1 in Audit logs when using GUI 'Seafile Client' app

### ISSUE THREAD

**Issue by rabb1t** [haiwen/seafile#1302]
We're using `seafile-pro-server-4.2.0` version.

Here are the typical http web requests in `FileAudit` table:
```
MariaDB [seahub]> select ip, device from FileAudit where device not like '%@%' group by ip order by device desc limit 25, 4;
+---------------+--------------------------------------------------------------------------+
| ip            | device                                                                   |
+---------------+--------------------------------------------------------------------------+
| 66.249.64.207 | Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) |
| 66.249.64.212 | Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) |
| 66.249.67.99  | Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) |
| 66.249.79.190 | Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) |
+---------------+--------------------------------------------------------------------------+
4 rows in set (0.01 sec)
```
And here is mine via Seafile Client app:
```
MariaDB [seahub]> select ip, device from FileAudit where device like 'rabbit@%' group by device;
+--------------+--------------------------------+
| ip           | device                         |
+--------------+--------------------------------+
| 127.0.0.1    | rabbit@rbt-vb.lan              |
+--------------+--------------------------------+
1 rows in set (0.00 sec)
```
And here I can see that the real IP address (from which user has logged in) determines correctly:
```
MariaDB [seahub]> select * from api2_tokenv2 where user like 'someuser@example%'\G
*************************** 1. row ***************************
             key: 825abd7df5857acc96fc231fa047218666240d2f
            user: someuser@example.org
        platform: windows
       device_id: 128cb81840a7f7f8b3d95dff8fb40db70d517ac7
     device_name: rbt-vb.lan
platform_version:
  client_version: 4.2.5
   last_accessed: 2015-07-02 12:38:39
   last_login_ip: 91.123.230.11          <=============== Client's real IP address
1 row in set (0.00 sec)
```
Is that some misconfiguration issues or the bug in GUI client?
