### ISSUE TITLE
SEAFILE_SERVER_HOSTNAME and https

### ISSUE THREAD

**Issue by Soarnoa** [haiwen/seafile#2059]
**EDIT: Sorry, I realized I posted this in the wrong Repo. Please close this issue.**

I'm using Seafile with Docker-compose, and behind Traefik with Let's encrypt.

When setting SEAFILE_SERVER_HOSTNAME in docker-compose, seafile does not check to see if the address starts with http:// or https:// . It will just append it to SERVICE_URL and FILE_SERVER_ROOT.

For example:
In my docker-compose file, I have the following: 
```
 seafile: 
    image: seafileltd/seafile
    container_name: Seafile
    restart: unless-stopped
    environment:
      SEAFILE_ADMIN_EMAIL: seafile@example.com
      SEAFILE_ADMIN_PASSWORD: My_Password
      SEAFILE_SERVER_HOSTNAME: https://seafile.example.com
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:seafile.example.com
      - traefik.port=80
      - traefik.backend=Seafile
      - traefik.docker.network=web
    volumes:
      - seafile:/shared
    networks:
      - web
```

If I check my settings panel, it shows: 
SERVICE_URL: http://https://seafile.example.com 
FILE_SERVER_ROOT: http://https://seafile.example.com/seafhttp

Removing http:// in the settings panel manually fixes the issue.
