### ISSUE TITLE
Seafile Docker - Connecting Via localhost Returns "502 Bad Gateway"

### ISSUE THREAD

**Issue by hwittenborn** [haiwen/seafile#2406]
I just got a seafile docker container up and running through the provided docker-compose file on the installation guide, but when I try to go to the site via localhost, it keeps returning a `502 Bad Gateway` error, with nothing in site inside the logs to what it could be.

Here's my `docker-compose.yml` file if it assists at all --

```
version: '2.0'
services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD= _*omitted*_  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/seafile/seafile-mysql/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "80:80"
#     - "443:443"  # If https is enabled, cancel the comment.
    expose:
      - "80"
    volumes:
      - /opt/seafile/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=localhost
      - DB_ROOT_PASSWD= _*omitted*_  # Requested, the value shuold be root's password of MySQL service.
#      - TIME_ZONE= _*omitted*_  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL= _*omitted*_ # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD= _*omitted*_     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME= _*omitted*_ # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net
```

The whole thing is behind an NGINX reverse proxy that proxies back to the docker container, but even a direct connect to the docker container without the reverse proxy yields the same 502 error.

Anything I'm missing?
