### ISSUE TITLE
[FEATURE REQUEST] Different temp file dir

### ISSUE THREAD

**Issue by danielvandenberg95** [haiwen/seafile#2526]
I'm storing my data on a gluster volume. Currently all tmp files are stored in the data directory, and therefore in glusterfs. As such, I'd love to see a setting introduced to change https://github.com/haiwen/seafile/blob/0fdc14d5175979919b7c741f6bb97bfaaacbbfbe/daemon/seafile-session.c#L157 to a config variable.

As a workaround I'm currently using the following in my swarm stack:
```
    volumes:
      - /mnt/gv0/seafile/files:/shared
      - type: tmpfs
        target: /shared/seafile/seafile-data/tmpfiles
      - type: tmpfs
        target: /shared/seafile/seafile-data/httptemp
      - type: tmpfs
        target: /shared/seafile/seafile-data/webdavtmp
```
