### ISSUE TITLE
Error setting up docker install.

### ISSUE THREAD

**Issue by apoorv569** [haiwen/seafile#2681]
I am trying to use the `docker compose` to install `seafile` in a `VM`.

These are the logs from `docker compose logs -f`
```
seafile-mysql      | 2023-06-11 20:03:02+00:00 [Note] [Entrypoint]: MariaDB init process done. Ready for start up.
seafile-mysql      |
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] Starting MariaDB 10.6.14-MariaDB-1:10.6.14+maria~ubu2004 source revision c93754d45e5d9379e3e23d7ada1d5f21d2711f66 as process 1
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: Number of pools: 1
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: Using generic crc32 instructions
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: Using Linux native AIO
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: Completed initialization of buffer pool
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: 128 rollback segments are active.
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: Creating shared tablespace for temporary tables
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: 10.6.14 started; log sequence number 42120; transaction id 14
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] Plugin 'FEEDBACK' is disabled.
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
seafile-mysql      | 2023-06-11 20:03:02 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] Server socket created on IP: '0.0.0.0'.
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] Server socket created on IP: '::'.
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] InnoDB: Buffer pool(s) load completed at 230611 20:03:02
seafile-mysql      | 2023-06-11 20:03:02 0 [Note] mariadbd: ready for connections.
seafile-mysql      | Version: '10.6.14-MariaDB-1:10.6.14+maria~ubu2004'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
seafile-mysql      | 2023-06-11 20:03:02 3 [Warning] Access denied for user 'seafile'@'172.25.0.4' (using password: YES)
seafile-mysql      | 2023-06-11 20:03:04 4 [Warning] Access denied for user 'seafile'@'172.25.0.4' (using password: YES)
```

And this is my `docker-compose.yml` file,
```yaml
version: '2.0'
services:
  db:
    image: mariadb:10.6
    container_name: seafile-mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./appdata/seafile/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    env_file:
      - .env
    ports:
      - "80:80"
  #   - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - /mnt/data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${DB_PASS}  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=MY_TIMEZONE  # Optional, default is UTC. Should be uncomment and set to your local time zone.
   #  - SEAFILE_ADMIN_EMAIL=me@example.com # Specifies Seafile admin user, default is 'me@example.com'.
   #  - SEAFILE_ADMIN_PASSWORD=asecret     # Specifies Seafile admin password, default is 'asecret'.
   #  - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
   #  - SEAFILE_SERVER_HOSTNAME=docs.seafile.com # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:
```

the storage for db is local in the VM only and storage for `seafile` container is `nfs` share with `all_squash, anongid=100, anonuid=1000, rw` options set.

I use a couple of other services like this only (with a nfs share) and they seem to work fine.
