### ISSUE TITLE
502 Bad Gateway (nginx/1.24.0) with LXC and Seafile Docker 

### ISSUE THREAD

**Issue by Jackovic** [haiwen/seafile#2685]
Hello,

I am trying to install Seafile Docker in a LXC container but I get : 502 Bad Gateway in my browser.

I use a web proxy (nginx) to forward to LXC container. It's configuration :
```
server {
        listen 80 proxy_protocol;
        listen [::]:80 proxy_protocol;

        server_name my.example.org;

        location / {

                include /etc/nginx/proxy_params;
                proxy_pass http://seafile.lxd;

        }

        real_ip_header proxy_protocol;
        set_real_ip_from 127.0.0.1;

}
```
I have a LXC container named "seafile" with Apache inside, it's configuration :
```
<VirtualHost *:80>
        ServerName my.example.org

        RewriteEngine On

        <Location /media>
            Require all granted
        </Location>

        # Stuff for seafile server
        ProxyPass /seafhttp http://127.0.0.1:8082
        ProxyPassReverse /seafhttp http://127.0.0.1:8082
        RewriteRule ^/seafhttp - [QSA,L]

        # Stuff for seahub
        SetEnvIf Authorization &quot;(.*)&quot; HTTP_AUTHORIZATION=$1
        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:8000/
        ProxyPassReverse / http://127.0.0.1:8000/

        ErrorLog ${APACHE_LOG_DIR}/seafile_error.log
        CustomLog ${APACHE_LOG_DIR}/seafile_access.log combined

</VirtualHost>
```

And, in this LXC container, i have the Seafile Docker running (with a user named "seafile") :
```
eafile@seafile:~$ docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS         PORTS                                                                              NAMES
33a724f5e281   seafileltd/seafile-mc:latest   "/sbin/my_init -- /s…"   4 seconds ago   Up 3 seconds   0.0.0.0:8082->8082/tcp, :::8082->8082/tcp, 0.0.0.0:8000->80/tcp, :::8000->80/tcp   seafile
9826e4225e66   memcached:1.5.6                "memcached -m 256"       5 seconds ago   Up 4 seconds   11211/tcp                                                                          seafile-memcached
1517a1d7f3c0   mariadb:10.1                   "docker-entrypoint.s…"   5 seconds ago   Up 4 seconds   3306/tcp                                                                           seafile-mysql

```

The Nginx version in the Seafile Docker is :
```
seafile@seafile:/root$ docker exec -it seafile bash
root@33a724f5e281:/opt/seafile# nginx -v
nginx version: nginx/1.24.0
```

Then I open a browser and enter http://my.example.org and get :
```
502 Bad Gateway
nginx/1.24.0
```
So, I guess, there is something wrong between Seafile Docker Nginx and Apache (also tried with Nginx in the LXC container, and same error).

Question : what can I do to solve this issue ? in web-proxy (Nginx 1.18, Ubuntu 22.04) ? in LXC container (Apache 2.4.52, Ubuntu 22.04) ? in Seafile Docker (Nginx 1.24).
Any help will be very appreciated.
Thank to the Seafile team for this software.
Best!
++

Jack

PS : I tested this same configuration WITHOUT LXC and it was working fine. But i decided to use LXC to organize my server.

**Comment by mlazzarotto** [comment]
I suggest searching Docker container logs for database connection problems.  
I initially had the same 502 but that was not because of my http configuration, but rather wrong MariaDB credentials and authorizations.

**Comment by Jackovic** [comment]
Hi mlazzarotto,

Thank you for the hint.
I search in /opt/seafile/logs/seafile.log but found nothing in this file (in the Docker container). Is it the right place to search ?

Here my docker-compose.yml with 'mypassword' as password for MySQL :
```
version: '2.0'
services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/seafile-mysql/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "8000:80"
      - "8082:8082"
#     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - /opt/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=mypassword  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=Etc/UTC  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=dev@example.org # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=XXXXXXX     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=my.example.org # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:
```
Then, when I connect to the MySQL database in the Docker container :
```
root@seafile:~# docker exec -it seafile-mysql /bin/bash
root@6654b3e2514e:/# mysql -uroot -pmypassword
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 14871
Server version: 10.1.48-MariaDB-1~bionic mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| ccnet_db           |
| information_schema |
| mysql              |
| performance_schema |
| seafile_db         |
| seahub_db          |
+--------------------+
6 rows in set (0.00 sec)

MariaDB [(none)]> use seafile_db
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [seafile_db]> show tables;
+----------------------+
| Tables_in_seafile_db |
+----------------------+
| Branch               |
| FileLockTimestamp    |
| FileLocks            |
| FolderGroupPerm      |
| FolderPermTimestamp  |
| FolderUserPerm       |
| GCID                 |
| GarbageRepos         |
| InnerPubRepo         |
| LastGCID             |
| OrgGroupRepo         |
| OrgInnerPubRepo      |
| OrgQuota             |
| OrgRepo              |
| OrgSharedRepo        |
| OrgUserQuota         |
| Repo                 |
| RepoFileCount        |
| RepoGroup            |
| RepoHead             |
| RepoHistoryLimit     |
| RepoInfo             |
| RepoOwner            |
| RepoSize             |
| RepoStorageId        |
| RepoSyncError        |
| RepoTokenPeerInfo    |
| RepoTrash            |
| RepoUserToken        |
| RepoValidSince       |
| RoleQuota            |
| SeafileConf          |
| SharedRepo           |
| SystemInfo           |
| UserQuota            |
| UserShareQuota       |
| VirtualRepo          |
| WebAP                |
| WebUploadTempFiles   |
+----------------------+
39 rows in set (0.00 sec)

MariaDB [seafile_db]> SELECT * FROM RepoFileCount;
+----+--------------------------------------+------------+
| id | repo_id                              | file_count |
+----+--------------------------------------+------------+
|  1 | 5a4a9308-01c9-4169-a927-c874f420b9b6 |          1 |
|  2 | 81471cf2-08c9-46d2-be24-90dfe6f68870 |          1 |
|  3 | 031ca845-d565-4fa2-a626-cd7cfaf5e23a |       3496 |
|  4 | b3f992c5-d230-4f77-a997-e6fa624f01b5 |      10509 |
|  6 | cbee47bb-a0f8-47b6-b035-05ed56db562d |       3174 |
|  7 | aff3a1bf-f200-459d-aa46-a90a7ffd66d8 |          1 |
|  8 | c39fd3e0-4133-4386-94a7-e2d8d5958b69 |          1 |
+----+--------------------------------------+------------+
7 rows in set (0.00 sec)
```

It seems everything is in right place and I can (and Seafile too) have an access to databases with root/mypassword ?

However i found in /var/log/nginx/seahub.error.log :
```
2023/06/24 23:23:07 [error] 68#68: *290 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: my.example.org, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "my.example.org"
2023/06/24 23:23:07 [error] 68#68: *290 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: my.example.org, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8000/favicon.ico", host: "my.example.org", referrer: "http://my.example.org/"
```
Maybe it is related to my issue ?
As I wrote at the end of my last message, the same configuration WITHOUT LXC was working nicely before (same docker-compose.yml).
I followed the section "Backup and recovery" on https://manual.seafile.com/docker/deploy_seafile_with_docker/ to copy database and data.

Any recommendations/tests I can do ?
Best!
++

Jack
