### ISSUE TITLE
Seafile Drive Client removes account when server temporarily unavailable

### ISSUE THREAD

**Issue by phiradd** [haiwen/seafile#2822]
I have got a seafile server running in a docker container on a QNAP NAS with the default configuration files (I have not changed any settings yet). It works very well but I have an issue whenever the NAS is not reachable, the account is removed from Seafile Drive Client 3.0.10 on  Windows 10, so that I have to relogin and put in all data for that. That is really annyoing. (It is only available in my local network).

Is there any way not to remove the account and just reconnect on server availability? I could not find anything in the configs.

I have changed some sensitive pw/paths in the logs/docker-compose. Please let me know if you need any other logs/config/info.

Thank you for your help!

**seadrive-gui.log**
```
[09/09/24 01:07:29] request failed for http://XXX.XXX.XXX.XXX:XXXX/api2/auth/ping/: {"detail":"User inactive or deleted"}

[09/09/24 01:07:29] Deleted account http://XXX.XXX.XXX.XXX:XXXX XXX@XXX.XX ce8e1d1
```

**docker-compose.yml**
```
services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=XXX # Required, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /share/Container/container-station-data/application/seafile/seafile-mysql:/var/lib/mysql  # Required, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc:11.0-latest
    container_name: seafile
    ports:
      - "9998:8080"
      - "9999:80"
    volumes:
      - /share/Container/container-station-data/application/seafile/seafile-data:/shared   # Required, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=XXX # Required, the value should be root's password of MySQL service.
      - TIME_ZONE=Europe/Berlin  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=XXX@XXX.io # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=XXX# Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=docs.seafile.com # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:

```
