### ISSUE TITLE
[BUG] No permission to access file

### ISSUE THREAD

**Issue by deffcolony** [haiwen/seafile#2854]
After upgrading from Seafile 11.x to Server Version 12.0.4, I encountered an issue where I could no longer download files via the WEBUI. The page displayed the following error message:

`No permission to access file`

To troubleshoot further, I created a shareable link with a direct download URL. However, when I visited the URL, I encountered another error:

`Internal server error`

This is happening to all files btw

## docker-compose.yml
```yaml
version: "3.8"

services:
  seafile-db:
    image: mariadb:latest
    container_name: seafile_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: REDACTED
      MYSQL_LOG_CONSOLE: true
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "9308:3306"
    networks:
      - seafile_net
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--connect",
          "--mariadbupgrade",
          "--innodb_initialized",
        ]
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 10

  seafile:
    image: seafileltd/seafile-mc:12.0-latest
    container_name: seafile
    environment:
      DB_HOST: seafile-db
      DB_PORT: 3306
      DB_ROOT_PASSWD: REDACTED
      TIME_ZONE: Etc/UTC
      SEAFILE_ADMIN_EMAIL: REDACTED
      SEAFILE_ADMIN_PASSWORD: REDACTED
      SEAFILE_SERVER_LETSENCRYPT: false
      SEAFILE_SERVER_HOSTNAME: seafile.DOMAIN.COM
    volumes:
      - ./data:/shared
    ports:
      - "8240:80"
    restart: unless-stopped
    depends_on:
      - seafile-db
      - seafile-memcached
    networks:
      - seafile_net

  seafile-memcached:
    image: memcached:1.6.29
    container_name: seafile_memcached
    command: memcached -m 256
    restart: unless-stopped
    networks:
      - seafile_net

networks:
  seafile_net:
    external: true
```

## seafile.log
```yaml
[2024-11-27 18:09:54] [INFO] start to serve on pipe client
[2024-11-27 18:20:38] [WARNING] http-tx-mgr.c(333): libcurl failed to POST http://127.0.0.1:8000api/v2.1/internal/repos/c3f01ea5-b64d-46ec-bb2f-3853122dc619/check-access/?path=00003-1067727885.png%2F: URL using bad/illegal format or missing URL.
```

## seahub.log
```yaml
2024-11-27 19:20:31,092 [ERROR] django.pylibmc:132 get MemcachedError: error 47 from memcached_get(:1:ENABLE_TWO_FACTOR_AUTH): (0x3147ea0) SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY,  host: memcached:11211 -> ./src/libmemcached/get.cc:233
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/seafile/seafile-server-12.0.4/seahub/thirdpart/django/core/cache/backends/memcached.py", line 75, in get
    return self._cache.get(key, default)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## video

https://github.com/user-attachments/assets/ec269bc8-4564-4c56-bc7d-b808ff2f9dd7

This also happens when creating a new file and then trying to download it i get:

`No permission to access file`

https://github.com/user-attachments/assets/c839937c-726b-4273-a6a3-3d7924027d3a

**Comment by SkywalkerSpace** [comment]
Hi, we have updated Seafile Docker deployment method in version 12.0. Please refer to the manual for upgrade, [Upgrade Seafile Docker](https://manual.seafile.com/12.0/upgrade/upgrade_docker/.) 
The old deployment method cannot start Seafile Docker correctly.

**Comment by deffcolony** [comment]
@freeplant The issue has not been solved, and I still encounter the same issues mentioned in my first post so i still get **No permission to access file** when attempting to download my own files from the WEBUI.

To clarify, I use Seafile with OnlyOffice and Traefik, and I have switched to the new Docker deployment settings as recommended. Below is the exact docker-compose.yml configuration I am using (ofcourse i redacted the sensitive info)

## docker-compose.yml
```yaml
version: "3.8"

services:
  seafile-db:
    image: mariadb:latest
    container_name: seafile_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: REDACTED
      MYSQL_LOG_CONSOLE: true
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - seafile_net
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--connect",
          "--mariadbupgrade",
          "--innodb_initialized",
        ]
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 10

  seafile:
    image: seafileltd/seafile-mc:12.0-latest
    container_name: seafile
    restart: unless-stopped
    ports:
      - "8240:80"
    volumes:
      - ./data:/shared
    environment:
      DB_HOST: seafile-db
      DB_PORT: 3306
      DB_ROOT_PASSWD: REDACTED
      DB_PASSWORD: REDACTED
      SEAFILE_MYSQL_DB_CCNET_DB_NAME: ccnet_db
      SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: seafile_db
      SEAFILE_MYSQL_DB_SEAHUB_DB_NAME: seahub_db
      TIME_ZONE: Etc/UTC
      INIT_SEAFILE_ADMIN_EMAIL: REDACTED@DOMAIN.COM
      INIT_SEAFILE_ADMIN_PASSWORD: REDACTED
      SEAFILE_SERVER_HOSTNAME: seafile.DOMAIN.COM
      SEAFILE_SERVER_PROTOCOL: http
      SEAFILE_SERVER_LETSENCRYPT: false #
      SITE_ROOT: /
      NON_ROOT: false
      JWT_PRIVATE_KEY: REDACTED
      ENABLE_SEADOC: false
      SEADOC_SERVER_URL: https://seafile.DOMAIN.COM/sdoc-server
    depends_on:
      - seafile-db
      - seafile-memcached
    networks:
      - seafile_net

  seafile-memcached:
    image: memcached:1.6.29
    container_name: seafile_memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile_net


  onlyoffice-postgresql:
    image: postgres:12
    container_name: seafile_onlyoffice_postgres
    environment:
      POSTGRES_DB: onlyoffice
      POSTGRES_USER: onlyoffice
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./onlyoffice/db:/var/lib/postgresql
    ports:
      - "9310:5432"
    restart: unless-stopped
    networks:
      - seafile_net

  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    container_name: seafile_onlyoffice_ds
    environment:
      DB_TYPE: postgres
      DB_HOST: onlyoffice-postgresql
      DB_PORT: 5432
      DB_USER: onlyoffice
      DB_NAME: onlyoffice
      AMQP_URI: amqp://guest:guest@onlyoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      JWT_ENABLED: true
      JWT_SECRET: onlyoffice
      JWT_HEADER: Authorization
      JWT_IN_BODY: true
    volumes:
      # Optional: see https://manual.seafile.com/deploy/only_office/
      #- ./onlyoffice/local.json:/etc/onlyoffice/documentserver/local.json
      #- ./onlyoffice/local-production-linux.json:/etc/onlyoffice/documentserver/local-production-linux.json
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/lib:/var/lib/onlyoffice
      - ./onlyoffice/logs:/var/log/onlyoffice
    ports:
      - "8243:80"
    restart: unless-stopped
    networks:
      - seafile_net

  onlyoffice-rabbitmq:
    image: rabbitmq:latest
    container_name: seafile_onlyoffice_rabbitmq
    volumes:
        - ./onlyoffice/rabbitmq/data:/var/lib/rabbitmq/
        - ./onlyoffice/rabbitmq/log:/var/log/rabbitmq
    restart: unless-stopped
    networks:
      - seafile_net

networks:
  seafile_net:
    external: true
```

## Additional Context:
1. I am not using Caddy, as Traefik was already configured and working perfectly with Seafile version 11.
2. I set the environment variable `SEAFILE_SERVER_LETSENCRYPT` to `false` since Traefik manages the HTTPS setup.
3. In version 11, everything functioned without any issues under this configuration.

Could you please assist in identifying why this issue is occurring with version 12? Let me know if further details are needed.
