### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS after login whilst using a CDN

### ISSUE THREAD

**Issue by Marthaarman** [haiwen/seafile#2864]
I'm using Bunny.net CDN to mask my own IP address. I did this before on CF which worked fine there but with bunny no more. 

I'm not so sure where to check and whether this is a seafile issue or not. But I lack the exact expertise to pinpoint any closer to the issue. 

This is the access.log stream and as you can see there are many redirects for some reason, right after I completed my 2FA:

```
[
    {
      "ClientAddr": "a.a.a.a:32679",
      "ClientHost": "a.a.a.a",
      "ClientPort": "32679",
      "ClientUsername": "-",
      "DownstreamContentSize": 165,
      "DownstreamStatus": 200,
      "Duration": 3772176,
      "OriginContentSize": 165,
      "OriginDuration": 3281207,
      "OriginStatus": 200,
      "Overhead": 490969,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 79,
      "RequestCount": 278884,
      "RequestHost": "mydomain.com",
      "RequestMethod": "POST",
      "RequestPath": "/seafhttp/repo/head-commits-multi/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:02.823556889+01:00",
      "StartUTC": "2024-12-20T11:49:02.823556889Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:02+01:00"
    },
    {
      "ClientAddr": "a.a.a.a:32679",
      "ClientHost": "a.a.a.a",
      "ClientPort": "32679",
      "ClientUsername": "-",
      "DownstreamContentSize": 165,
      "DownstreamStatus": 200,
      "Duration": 3619440,
      "OriginContentSize": 165,
      "OriginDuration": 3163321,
      "OriginStatus": 200,
      "Overhead": 456119,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 79,
      "RequestCount": 278885,
      "RequestHost": "mydomain.com",
      "RequestMethod": "POST",
      "RequestPath": "/seafhttp/repo/head-commits-multi/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:32.852042706+01:00",
      "StartUTC": "2024-12-20T11:49:32.852042706Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:32+01:00"
    },
    {
      "ClientAddr": "b.b.b.b:59971",
      "ClientHost": "b.b.b.b",
      "ClientPort": "59971",
      "ClientUsername": "-",
      "DownstreamContentSize": 0,
      "DownstreamStatus": 302,
      "Duration": 18096668,
      "OriginContentSize": 0,
      "OriginDuration": 17703508,
      "OriginStatus": 302,
      "Overhead": 393160,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 0,
      "RequestCount": 278886,
      "RequestHost": "mydomain.com",
      "RequestMethod": "GET",
      "RequestPath": "/accounts/login/?next=/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:54.84544325+01:00",
      "StartUTC": "2024-12-20T11:49:54.84544325Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:54+01:00"
    },
    {
      "ClientAddr": "b.b.b.b:59971",
      "ClientHost": "b.b.b.b",
      "ClientPort": "59971",
      "ClientUsername": "-",
      "DownstreamContentSize": 0,
      "DownstreamStatus": 302,
      "Duration": 28232809,
      "OriginContentSize": 0,
      "OriginDuration": 27628527,
      "OriginStatus": 302,
      "Overhead": 604282,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 0,
      "RequestCount": 278887,
      "RequestHost": "mydomain.com",
      "RequestMethod": "GET",
      "RequestPath": "/accounts/login/?next=/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:54.924998278+01:00",
      "StartUTC": "2024-12-20T11:49:54.924998278Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:54+01:00"
    },
    {
      "ClientAddr": "b.b.b.b:59971",
      "ClientHost": "b.b.b.b",
      "ClientPort": "59971",
      "ClientUsername": "-",
      "DownstreamContentSize": 0,
      "DownstreamStatus": 302,
      "Duration": 26959157,
      "OriginContentSize": 0,
      "OriginDuration": 26599087,
      "OriginStatus": 302,
      "Overhead": 360070,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 0,
      "RequestCount": 278888,
      "RequestHost": "mydomain.com",
      "RequestMethod": "GET",
      "RequestPath": "/accounts/login/?next=/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:55.003472202+01:00",
      "StartUTC": "2024-12-20T11:49:55.003472202Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:55+01:00"
    },
    {
      "ClientAddr": "b.b.b.b:59971",
      "ClientHost": "b.b.b.b",
      "ClientPort": "59971",
      "ClientUsername": "-",
      "DownstreamContentSize": 0,
      "DownstreamStatus": 302,
      "Duration": 28982961,
      "OriginContentSize": 0,
      "OriginDuration": 28569302,
      "OriginStatus": 302,
      "Overhead": 413659,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 0,
      "RequestCount": 278889,
      "RequestHost": "mydomain.com",
      "RequestMethod": "GET",
      "RequestPath": "/accounts/login/?next=/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:55.083932502+01:00",
      "StartUTC": "2024-12-20T11:49:55.083932502Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:55+01:00"
    },
    {
      "ClientAddr": "b.b.b.b:59971",
      "ClientHost": "b.b.b.b",
      "ClientPort": "59971",
      "ClientUsername": "-",
      "DownstreamContentSize": 0,
      "DownstreamStatus": 302,
      "Duration": 28115718,
      "OriginContentSize": 0,
      "OriginDuration": 27752806,
      "OriginStatus": 302,
      "Overhead": 362912,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 0,
      "RequestCount": 278890,
      "RequestHost": "mydomain.com",
      "RequestMethod": "GET",
      "RequestPath": "/accounts/login/?next=/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:55.164424392+01:00",
      "StartUTC": "2024-12-20T11:49:55.164424392Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:55+01:00"
    },
    {
      "ClientAddr": "b.b.b.b:59971",
      "ClientHost": "b.b.b.b",
      "ClientPort": "59971",
      "ClientUsername": "-",
      "DownstreamContentSize": 0,
      "DownstreamStatus": 302,
      "Duration": 28598965,
      "OriginContentSize": 0,
      "OriginDuration": 28210135,
      "OriginStatus": 302,
      "Overhead": 388830,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 0,
      "RequestCount": 278891,
      "RequestHost": "mydomain.com",
      "RequestMethod": "GET",
      "RequestPath": "/accounts/login/?next=/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:55.408017096+01:00",
      "StartUTC": "2024-12-20T11:49:55.408017096Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:55+01:00"
    },
    {
      "ClientAddr": "b.b.b.b:59971",
      "ClientHost": "b.b.b.b",
      "ClientPort": "59971",
      "ClientUsername": "-",
      "DownstreamContentSize": 0,
      "DownstreamStatus": 302,
      "Duration": 28530558,
      "OriginContentSize": 0,
      "OriginDuration": 28149053,
      "OriginStatus": 302,
      "Overhead": 381505,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 0,
      "RequestCount": 278892,
      "RequestHost": "mydomain.com",
      "RequestMethod": "GET",
      "RequestPath": "/accounts/login/?next=/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:55.502285329+01:00",
      "StartUTC": "2024-12-20T11:49:55.502285329Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:55+01:00"
    },
    {
      "ClientAddr": "b.b.b.b:59971",
      "ClientHost": "b.b.b.b",
      "ClientPort": "59971",
      "ClientUsername": "-",
      "DownstreamContentSize": 0,
      "DownstreamStatus": 302,
      "Duration": 27511531,
      "OriginContentSize": 0,
      "OriginDuration": 27140106,
      "OriginStatus": 302,
      "Overhead": 371425,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 0,
      "RequestCount": 278893,
      "RequestHost": "mydomain.com",
      "RequestMethod": "GET",
      "RequestPath": "/accounts/login/?next=/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:55.577782506+01:00",
      "StartUTC": "2024-12-20T11:49:55.577782506Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:55+01:00"
    },
    {
      "ClientAddr": "b.b.b.b:59971",
      "ClientHost": "b.b.b.b",
      "ClientPort": "59971",
      "ClientUsername": "-",
      "DownstreamContentSize": 0,
      "DownstreamStatus": 302,
      "Duration": 29685686,
      "OriginContentSize": 0,
      "OriginDuration": 29271423,
      "OriginStatus": 302,
      "Overhead": 414263,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 0,
      "RequestCount": 278894,
      "RequestHost": "mydomain.com",
      "RequestMethod": "GET",
      "RequestPath": "/accounts/login/?next=/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:55.653147127+01:00",
      "StartUTC": "2024-12-20T11:49:55.653147127Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:55+01:00"
    },
    {
      "ClientAddr": "b.b.b.b:59971",
      "ClientHost": "b.b.b.b",
      "ClientPort": "59971",
      "ClientUsername": "-",
      "DownstreamContentSize": 0,
      "DownstreamStatus": 302,
      "Duration": 25355246,
      "OriginContentSize": 0,
      "OriginDuration": 25038923,
      "OriginStatus": 302,
      "Overhead": 316323,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 0,
      "RequestCount": 278895,
      "RequestHost": "mydomain.com",
      "RequestMethod": "GET",
      "RequestPath": "/accounts/login/?next=/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:55.743899583+01:00",
      "StartUTC": "2024-12-20T11:49:55.743899583Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:55+01:00"
    },
    {
      "ClientAddr": "b.b.b.b:59971",
      "ClientHost": "b.b.b.b",
      "ClientPort": "59971",
      "ClientUsername": "-",
      "DownstreamContentSize": 0,
      "DownstreamStatus": 302,
      "Duration": 9562631,
      "OriginContentSize": 0,
      "OriginDuration": 9363634,
      "OriginStatus": 302,
      "Overhead": 198997,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 0,
      "RequestCount": 278896,
      "RequestHost": "mydomain.com",
      "RequestMethod": "GET",
      "RequestPath": "/accounts/login/?next=/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:49:55.822424698+01:00",
      "StartUTC": "2024-12-20T11:49:55.822424698Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:49:55+01:00"
    },
    {
      "ClientAddr": "a.a.a.a:32679",
      "ClientHost": "a.a.a.a",
      "ClientPort": "32679",
      "ClientUsername": "-",
      "DownstreamContentSize": 165,
      "DownstreamStatus": 200,
      "Duration": 1572379,
      "OriginContentSize": 165,
      "OriginDuration": 1397738,
      "OriginStatus": 200,
      "Overhead": 174641,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 79,
      "RequestCount": 278897,
      "RequestHost": "mydomain.com",
      "RequestMethod": "POST",
      "RequestPath": "/seafhttp/repo/head-commits-multi/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:50:02.872841762+01:00",
      "StartUTC": "2024-12-20T11:50:02.872841762Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:50:02+01:00"
    },
    {
      "ClientAddr": "a.a.a.a:32679",
      "ClientHost": "a.a.a.a",
      "ClientPort": "32679",
      "ClientUsername": "-",
      "DownstreamContentSize": 165,
      "DownstreamStatus": 200,
      "Duration": 3001300,
      "OriginContentSize": 165,
      "OriginDuration": 2677788,
      "OriginStatus": 200,
      "Overhead": 323512,
      "RequestAddr": "mydomain.com",
      "RequestContentSize": 79,
      "RequestCount": 278899,
      "RequestHost": "mydomain.com",
      "RequestMethod": "POST",
      "RequestPath": "/seafhttp/repo/head-commits-multi/",
      "RequestPort": "-",
      "RequestProtocol": "HTTP/1.1",
      "RequestScheme": "https",
      "RetryAttempts": 0,
      "RouterName": "seafile-secure@docker",
      "ServiceAddr": "172.30.0.3:80",
      "ServiceName": "seafile@docker",
      "ServiceURL": "http://172.30.0.3:80",
      "StartLocal": "2024-12-20T12:50:32.893801828+01:00",
      "StartUTC": "2024-12-20T11:50:32.893801828Z",
      "TLSCipher": "TLS_AES_128_GCM_SHA256",
      "TLSVersion": "1.3",
      "entryPointName": "websecure",
      "level": "info",
      "msg": "",
      "time": "2024-12-20T12:50:32+01:00"
    }
  ]
```

For some reason, after authenticating, another ip address (b.b.b.b) is given rather than a.a.a.a which were the first 2 ip addresses. 

Seafile docker:

```
services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Required, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /opt/seafile-mysql/db:/var/lib/mysql  # Required, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net
    restart: always

  memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
    restart: always
  seafile:
    image: seafileltd/seafile-mc:11.0-latest
    container_name: seafile
    restart: always
    ports:
      - "9001:80"
    volumes:
      - ${SEAFILE_DATA_PATH}:/shared   # Required, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${MYSQL_ROOT_PASSWORD}  # Required, the value should be root's password of MySQL service.
      - TIME_ZONE=Europe/Amsterdam  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL} # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_HOSTNAME=mydomain.com # Specifies your host name if https is enabled.
      - FORCE_HTTPS_IN_CONF=false
      #- BUNNY_ZONE_ID=451668
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seafile-secure.entrypoints=websecure"
      - "traefik.http.routers.seafile-secure.rule=Host(`mydomain.com`)"
      - "traefik.http.routers.seafile-secure.tls=true"
      - "traefik.http.routers.seafile-secure.tls.certresolver=bunny"
      - "traefik.http.routers.seafile-secure.service=seafile"
      - "traefik.http.services.seafile.loadbalancer.server.port=80"
      - "traefik.docker.network=network_traefik_external"
networks:
  seafile-net:
  traefik:
    name: network_traefik_external
    external: true

```

Traefik.yml
```
log:
  level: DEBUG 
  filePath: "/var/log/traefik/traefik.log"  
  maxBackups: 3
accessLog:
  filePath: "/var/log/traefik/access.log"   
  bufferingSize: 100                       
  filters:   
    statusCodes: ["200-399"]
  format: json

api:
  dashboard: true # Optional can be disabled
  insecure: true # Optional can be disabled
  debug: true # Optional can be Enabled if needed for troubleshooting 
entryPoints:
  web:
    address: ":80"
  # Optional if you want to redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
certificatesResolvers:
  bunny:
    acme:
      email: mail@mydomain.com
      storage: /certs/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      dnsChallenge:
        provider: bunny
        delayBeforeCheck: 90

```

Does work perfectly fine when using the local ipaddress:9001 but ofcourse I want to use domain name. 
Any suggestions?
