### ISSUE TITLE
Database Access denied for user 

### ISSUE THREAD

**Issue by scoop96** [haiwen/seafile#2872]
docker of seafile pro not starting (barely modified) 

followed this tutorial 

https://manual.seafile.com/latest/setup/setup_pro_by_docker/

Only modified the volume of the seafile docs and created a local folder in the folder of /seafile to have everything close.
NO USERNAMES OR VARIABLES were modified. 

the docker volume is mounted inside of the docker compose file as this:
```
volumes:
  seafile:
    name: seafile
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.131,nolock,soft,rw"
      device: ":/CartographerNFS/seafile/data"
```

![image](https://github.com/user-attachments/assets/d96200fa-11e7-426b-819e-7455060a0f0b)

I have to leave in 5 ( i will upload the files later) 

thank you
